name: SpawnerChance
main: com.flyaway.spawnerchance.SpawnerChance
version: 1.3.0
api-version: "1.21"
description: Плагин дающий шанс выпадения спавнера. Ограничивает мобов, которых можно применять к спавнеру.
author: FlyAwayMaking
website: https://github.com/flyawaymaking
softdepend:
  - LuckPerms

commands:
  spawnerchance:
    description: Основная команда SpawnerChance
    usage: /<command> [tempchance|reload|info]
    permission: spawner.command.use

permissions:
  spawner.dropchance.*:
    description: Шанс выпадения спавнера в %
    default: false
  spawner.bypass:
    description: Обход ограничений на установку мобов в спавнер
    default: op
  spawner.command.use:
    description: Доступ к командам плагина
    default: op
